queue:
  name:
variables:
  python.version: "3.6"

steps:
  - task: "UsePythonVersion@0"
    displayName: "Use Python $(python.version)"
    inputs:
      versionSpec: "$(python.version)"

  - script: "bash -c 'find src tests -name \"*.py\" | xargs pylint; rc=$$?; ((($rc&(1+2+32))>0)) && exit $$rc || exit 0'"
    displayName: "Lint using pylint"
    continueOnError: true

  - script: "python -m pip install --upgrade pip && pip install .[ftp,hdfs,s3,sftp,dev]"
    displayName: "Install package + requirements"
    env:
      SLUGIFY_USES_TEXT_UNIDECODE: "yes"

  - script: "py.test tests --junitxml=.junit/test-results.xml --cov=src/airflow_fs --cov-report=html --cov-report=xml"
    displayName: "Run tests using pytest"
    env:
      AWS_ACCESS_KEY_ID: "foobar_key"
      AWS_SECRET_ACCESS_KEY: "foobar_secret"

  - task: PublishTestResults@2
    displayName: "Publish test results"
    inputs:
      testResultsFiles: "**/test-results.xml"
      testRunTitle: "Python $(python.version)"

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish test coverage results'
    inputs:
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
      codecoverageTool: Cobertura
