version: 2
jobs:
  lint:
    working_directory: ~/circleci
    docker:
      - image: python:python-3.6.8-stretch
    steps:
      - checkout
      - run:
          name: Install pylint
          command: pip install pylint
      - run:
          name: Run pylint
          command: pylint src
  test:
    working_directory: ~/circleci
    docker:
      - image: jrderuiter/airflow-fs-ci
    steps:
      - checkout
      - run:
          name: Fix passwordless ssh
          command: |
            rm ~/.ssh/id_rsa &&
            ssh-keygen -q -N "" -t rsa -f ~/.ssh/id_rsa &&
            cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
      - run:
          name: Bootstrap services
          command: '/bin/bash /usr/sbin/bootstrap.sh'
      - run:
          name: Install package
          command: 'SLUGIFY_USES_TEXT_UNIDECODE=yes pip install .[all,dev]'
      - run:
          name: Run tests
          command: 'airflow initdb && pytest tests -vvv'
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
